### ISSUE TITLE
Can't build openssl v0.7.14

### ISSUE THREAD

**Issue by ErwanTLG** [vityafx/challonge-rs#9]
I am working on a project. Until yet, I didn't use challonge-rs. But after adding `challonge = "0.4"` to my project's dependencies, I get the following error when building the project: `error: failed to run custom build command for 'openssl v0.7.14'`. This error disappears when I remove challonge from my dependencies. 
I was wondering if you had a fix for this issue.

**Comment by iddm** [comment]
Hi! I am sorry for not answering faster. I'll take a look.

**Comment by iddm** [comment]
This must be happening due to an old hyper dependency. I need to rewrite everything to `reqwest` instead. I have started doing that, should finish this week. Note that I also was in the works of upgrading the whole crate due to the most recent dependencies and the code itself to use proper abstractions.

**Comment by ErwanTLG** [comment]
Nice to hear !
I can help a bit if you want, just not sure where to start or what's currently needed the most.

**Comment by iddm** [comment]
Okay, had some issues and couldn't start working right after I left the comment there. I am re-working the crate now, but it will surely take a while, it occurred to me that the code was really written according to ancient practices in rust (for example, initially it was not even using serde but `rustc_deserialize` instead) and other stuff. In the meanwhile, I hope the [`toornament`](https://github.com/vityafx/toornament-rs) crate might help you.
UPD: though the code quality in toornament is much better, the api has changed a bit and they released the 2nd version of it, leaving the 1st version which the crate uses - deprecated. I am negotiating with them to give me access once more so that I could update the crate there.

**Comment by iddm** [comment]
I have just published a version 0.5.0 where I moved from `hyper` to `reqwest` which either uses a more modern `openssl` dependency or even `rustls`. Please check it out.

A short changelog:
1. Moved to `reqwest` with `rustls` backend used by default.
2. Added features for toggling `rustls` on and off.
3. Updated dependencies.
4. Made the code more up-to-date to the current coding practices in Rust (formatting, clippy, testing).
5. Moved to rust edition 2018.
6. Added CI and nightly jobs using GitHub actions and funding information.

You should be able to build now just fine.

**Comment by ErwanTLG** [comment]
Thank you very much !
